### ISSUE TITLE
Increase PHP Memory Limit?

### ISSUE THREAD

**Issue by adamkingfisher** [markoshust/docker-magento#102]
Hi Mark,

Great job on this Repo, it's really helpful. This could be a gap in my docker knowledge but using your setup how could I go about changing the php.ini variables so that they won't reset when I upgrade from PHP 7.2-fpm to 7.3?

Many thanks again,
Adam

**Comment by markoshust** [comment]
You can create an "images/php" directory within your project root. Then in your `docker-compose.yml` file, instead of referencing:

```
image: markoshust/magento-php:7.1-fpm-9
```
change it to:
```
build: images/php
```

Then within your `images/php` directory, create a `Dockerfile` with the contents:
```
FROM markoshust/magento-php:7.1-fpm-9

COPY conf/php.ini
```
Then you can define your php.ini file at `images/php/conf/php.ini`

You can see a similar example of how I am doing this for nginx by checking out the m1 compose setup at https://github.com/markoshust/docker-magento/tree/master/compose/magento-1
