### ISSUE TITLE
Issue Running One Line Setup

### ISSUE THREAD

**Issue by ryanjavens** [markoshust/docker-magento#103]
First of all, thanks for this repository. I watched your webinar about this project and am really excited about getting Magento running in Docker for myself! 

I'm currently having an issue trying to run the one line setup command that you have in your documentation. 

Here is the command I'm running:`curl -s https://raw.githubusercontent.com/markoshust/docker-magento/master/lib/onelinesetup\|bash -s - mymagento.test 2.2.6`

I get the following from my terminal:
```
curl: option -: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```

Is there a flag that I should be setting after the `-` before 'mymagento.test'? 

Thanks!

**Comment by ryanjavens** [comment]
Update:

Got it working when I modified the command to look like this: `curl -s https://raw.githubusercontent.com/markoshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test 2.2.6`

Mismatched curl versions potentially? I'm not sure why my terminal was being finicky about the `-` vs `--`.

**Comment by corbinu** [comment]
@ryanjavens Is it possible you are using zsh? I found the install script only works with bash.

**Comment by ryanjavens** [comment]
@corbinu yes I am actually. Good call!

**Comment by corbinu** [comment]
@markoshust Would you be open to a PR that converts the setup scripts into a CLI app? I could write it in Rust, Node.js or PHP there are pros and cons of each.

Rust would be my first choice. It would produce a nice binary anybody can use. However not everybody knows how to code it. 

Node would be my second choice. It is easy for people to edit and pretty much everybody has it. Especially since so many dev tools (including Magento PWA Studio) use it.

PHP My last choice. Obviously makes sense cause Magento is in it. However people maybe using this docker container specifically not to have it on their system.

**Comment by markoshust** [comment]
@corbinu yes. going to be in another repo/project though ;) i think node.js is solid choice since i'm familiar with it.

open for contributions, but i never merge code that is complex or hard to understand. needs to be stupid. simple. 😄 

anyways, the double dash works in bash so i merged this in to make the code more portable.
https://github.com/markoshust/docker-magento/commit/58527dbaa46d5a76e8bfe11b07a25b9a96be6aa1

**Comment by ryanjavens** [comment]
Thanks @markoshust and @corbinu!
