### ISSUE TITLE
High CPU HyperKit on MacBook Pro 

### ISSUE THREAD

**Issue by sajidunnar** [markoshust/docker-magento#93]
Hello 

Sorry it's not problem of this container but docker itself maybe someone has a solution as I am running Magento 2.2.3 with docker-composer but its really hard to work as hyperkit process takes around 200% CPU and with phpstorm it's hard to work, I have 16gb RAM though and SSD installed
any workaround for this problem?

**Comment by markoshust** [comment]
Make sure you have caching enabled... ex. `bin/magento cache:enable`. If you do it's most likely a problem with your version of Docker for Mac, I would try reinstalling, but I've only ever experienced this issue when I had caching disabled.

**Comment by joshdavenport** [comment]
Just something to add to this in case anyone else stumbles on this issue. I've been wrestling with this for what seems like forever. Constant high CPU usage basically crippling my MBP and turning it into a battery draining radiator, it turns out it is the cron container that is causing constant CPU spikes.

![image](https://user-images.githubusercontent.com/757828/68766031-0455cb00-0616-11ea-875b-7648b7014af7.png)

That is pre and post temporarily commenting Magento related crontab tasks in the cron container. Before, when not hitting any frontend page, CPU in Activity Monitor visibly sits around 100-200 constantly and without never raises above 2.

No idea if this issue sits primarily with the Magento codebase, these images, or with docker itself, but it sure is a pain!

**Comment by markshust** [comment]
yep -- uses a lot of CPU https://github.com/markshust/docker-magento/blob/master/compose/magento-2/docker-compose.yml#L43

**Comment by markshust** [comment]
i'd recommend to only enable the cron if needed or if you are working on cron-specific tasks. if anyone has any idea why the cron takes up so much CPU please let me know -- i believe this is most likely magento-related as opposed to this docker repo-related.
