### ISSUE TITLE
Cannot run magento setup page

### ISSUE THREAD

**Issue by nmklong** [markoshust/docker-magento#95]
Hi, i'm having a blank page after everything was up and running
![screen shot 2018-06-11 at 12 14 37](https://user-images.githubusercontent.com/1017308/41252114-10ad5e02-6d71-11e8-9368-ad3d40a4f1d9.png)

Looking at the the log i can see this

![screen shot 2018-06-11 at 12 15 20](https://user-images.githubusercontent.com/1017308/41252166-33ba62be-6d71-11e8-875c-b88ecd88daf3.png)

I'm pretty new to docker so i tried editing the conf files as suggested here
https://github.com/magento/magento2/issues/2504

But still can't get it working, i tried removing the images and containers after changing the files

**Comment by sanjay-wagento** [comment]
@nmklong , Please set correct user and group to Magento source (chmod -R app:app /var/www/html)
Remove magento cache and other directory by rm -rf /var/www/html/var/*

**Comment by markoshust** [comment]
I need full steps to replicate in order to make sure this is a real issue. I've been editing nginx files with no probs. My guess is that the path changed somehow using another nginx config setup. See https://github.com/markoshust/docker-magento/tree/master/compose/magento-1 for example of how to override/use nginx config files.
